# Generated by Django 4.2.1 on 2023-05-20 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsessionmodel',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatsessionmodel',
            name='handler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handler_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
