# Generated by Django 4.2.1 on 2023-05-20 13:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='N/A', max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceTagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(default='N/A', max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceTierModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.IntegerField(default=0)),
                ('sub_title', models.CharField(default='N/A', max_length=125)),
                ('description', models.TextField(default='N/A', max_length=225)),
                ('average_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.servicesmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceReviewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.servicesmodel')),
            ],
        ),
    ]
