# Generated by Django 4.2.1 on 2023-05-20 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0002_servicesmodel_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesmodel',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='ServicesOngoingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_booked', models.DateTimeField(auto_now_add=True)),
                ('milestones', models.IntegerField(default=1)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('time_spent', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('time_est', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.servicetiermodel')),
            ],
        ),
    ]
