# Generated by Django 4.2.1 on 2023-05-20 19:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_servicesmodel_date_created_servicesongoingmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesongoingmodel',
            name='date_first_meetup',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='servicesongoingmodel',
            name='date_last_meetup',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
