# Generated by Django 4.2.1 on 2023-05-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_servicesongoingmodel_date_first_meetup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesongoingmodel',
            name='status',
            field=models.IntegerField(choices=[(0, 'Initial Meetup'), (1, 'Working'), (2, 'Waiting For Review'), (3, 'Meeting'), (4, 'Change Requirements'), (5, 'Finalizing'), (6, 'Presenting'), (7, 'Finished')], default=0),
        ),
    ]
