# Generated by Django 4.2.1 on 2023-05-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_payment_id_usercardmodel_useraddressmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=None, max_length=125, unique=True),
        ),
    ]
