# Generated by Django 4.2.1 on 2023-05-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Admin'), (1, 'Resource Manager'), (2, 'Customer Handler'), (3, 'Customer')], default=3),
        ),
    ]
