# Generated by Django 4.2.1 on 2023-05-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_role_usergroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercardmodel',
            name='brand',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
